name: CI
on: [push, pull_request]
env:
  HTTPTOOLKIT_SERVER_DISABLE_AUTOUPDATE: 1 # Don't try to autoupdate during builds
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: httptoolkit/act-build-base:v3.0.0
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - run: npm install -g npm@^8

      - name: Install 7-zip
        run: |
          curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          # Ditto but for Google:
          curl -sL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

          sudo apt-get update
          sudo apt-get install -y p7zip-full xterm

      - run: npm ci
        env:
          NPM_CONFIG_UNSAFE_PERM: true

      - run: npm run build:src

      - run: npm run build:release
        env:
          SENTRY_AUTH_TOKEN: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && secrets.SENTRY_AUTH_TOKEN) || '' }}
          SENTRY_ORG: http-toolkit
          SENTRY_PROJECT: httptoolkit-server
          NPM_CONFIG_UNSAFE_PERM: true

      - uses: actions/upload-artifact@v4
        with:
          name: distributables
          path: build/dist/*
          if-no-files-found: error

  publish:
    name: Publish a release
    runs-on: "ubuntu-22.04"
    needs:
      - build
    steps:
      - name: Get our distributables
        uses: actions/download-artifact@v4
        with:
          name: distributables
          path: distributables

      - name: Upload server release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAH }}
          file: ./distributables/*/*
          file_glob: true
          tag: refs/heads/main
          overwrite: true

      - name: Upload latest manifest
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAH }}
          file: ./distributables/latest-manifest/*
          file_glob: true
          tag: latest-manifest
          overwrite: true
